mappings:
  ImageGalleryPage: Sunnysideup\ImagegalleryBasic\ImageGalleryPage
  ImageGalleryPageController: Sunnysideup\ImagegalleryBasic\ImageGalleryPageController
  ImageGalleryHolder: Sunnysideup\ImagegalleryBasic\ImageGalleryHolder
  ImageGalleryHolderController: Sunnysideup\ImagegalleryBasic\ImageGalleryHolderController
  ImageGalleryEntry: Sunnysideup\ImagegalleryBasic\Model\ImageGalleryEntry
